name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
env:
  REACT_APP_SITE_KEY: ${{ secrets.SITE_KEY }}
  REACT_APP_SECRET_KEY: ${{ secrets.SECRET_KEY }}
  REACT_APP_NAME: ${{ secrets.APP_NAME }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HERDUCATE_NONPROFIT }}"
          channelId: live
          projectId: ${{ secrets.PROJECT_ID }}
